#!/bin/zsh
# Path configuration for Jasper's Macbook Pro.
# Adds necessary directories to PATH, PYTHONPATH,
# LD_LIBRARY_PATH, DYLD_LIBRARY_PATH, etc.
#
# Source me in ~/.zshrc, either directly via the path to
# this file in the shell-configs repo, or by linking this
# file to ~/.path and sourcing that.

export PATH=\
/Applications/Julia-1.7.app/Contents/Resources/julia/bin:\
$HOME/Library/'Application Support'/fnm:\
$HOME/repos/jasper-tms/npimage/scripts:\
$HOME/repos/nely/scapeio/scripts:\
$HOME/repos/nely/DeMotion5D:\
$HOME/Library/Python/3.12/bin:\
$HOME/repos/htem/run_elastix:\
$HOME/software/executables:\
$HOME/software:\
$PATH

#$HOME/repos:\
#/opt/homebrew/opt/qt@5/bin:\ #for pip install pyqt5 to succeed

# brew (arm64 installation - Apple M1 architecture)
# Install instructions say to put the single line `eval "$(/opt/homebrew/bin/brew shellenv)"` below but instead I've put the lines output by `brew shellenv` here for explicitness:
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
#export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"  # This is not related to brew install but to using a brew package

# brew (x86_64 installation - by using `arch -x86` when installing brew on Apple M1 architecture)
#export PATH=/usr/local/homebrew/bin:$PATH
#alias brew="arch -x86_64 brew"  # Enforce that all brew commands use x86_64-compatibility. Note that this eliminates optimizations for Apple M1 architecture in order to gain compatibility with much more software

# Add brew-installed python3.10 packages to PYTHONPATH
#export PYTHONPATH=/opt/homebrew/lib/python3.10/site-packages${PYTHONPATH+:$PYTHONPATH}
# Add graph-tools to PYTHONPATH. This path says python3.12 but it looks like
# its backwards-compatible with older python versions.
export PYTHONPATH=\
/opt/homebrew/Cellar/graph-tool/2.92/lib/python3.13/site-packages\
${PYTHONPATH+:$PYTHONPATH}


# elastix/transformix
export LD_LIBRARY_PATH=$HOME/software/elastix-5.2.0-mac/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=$HOME/software/elastix-5.2.0-mac/lib${DYLD_LIBRARY_PATH+:$DYLD_LIBRARY_PATH}


# PATH for the Google Cloud SDK.
if [ -f '/Users/jasper/software/google-cloud-sdk/path.zsh.inc' ]; then
    . '/Users/jasper/software/google-cloud-sdk/path.zsh.inc'
fi
# Shell command completion for gcloud.
if [ -f '/Users/jasper/software/google-cloud-sdk/completion.zsh.inc' ]; then
    . '/Users/jasper/software/google-cloud-sdk/completion.zsh.inc'
fi
