#!/bin/bash

if [ -e "$HOME/software/Fiji.app" ]; then
    fiji_dir="$HOME/software/Fiji.app"
elif [ -e "$HOME/Fiji.app" ]; then
    fiji_dir="$HOME/Fiji.app"
elif [ -e "/Applications/Fiji.app" ]; then
    fiji_dir="/Applications/Fiji.app"
fi

if "$IS_LINUX"; then
    if [ "$#" -gt 0 ]; then
        args=()
        for arg in "$@"; do
            args+=("$(realpath "$arg")")
        done
        "$fiji_dir/ImageJ-linux64" "${args[@]}"
    else
        "$fiji_dir/ImageJ-linux64"
    fi
elif "$IS_MAC"; then
    "$fiji_dir/Contents/MacOS/ImageJ-macosx" "$@"
fi
