#!/bin/bash

if [ -e "$HOME/software/Fiji.app" ]; then
    fiji_dir="$HOME/software/Fiji.app"
elif [ -e "$HOME/Fiji.app" ]; then
    fiji_dir="$HOME/Fiji.app"
elif [ -e "/Applications/Fiji.app" ]; then
    fiji_dir="/Applications/Fiji.app"
fi

if [ "$(uname)" = "Linux" ]; then
    if [ "$#" -gt 0 ]; then
        $fiji_dir/ImageJ-linux64 $(realpath "$@")
    else
        $fiji_dir/ImageJ-linux64
    fi
elif [ "$(uname)" = "Darwin" ]; then
    $fiji_dir/Contents/MacOS/ImageJ-macosx "$@"
fi
