#!/bin/bash

if ls frames/* &> /dev/null; then
    echo "Files already exist at frames/*. Go delete them first. Aborting."
    exit 1
fi
mkdir -p frames

if [ "${1:0:1}" = "/" ]; then
    # Absolute paths
    prefix=""
else
    # Relative paths
    prefix="../"
fi

f=0
ext=${1##*.} #file extension (e.g. tif, jpg)
for i in "$@"; do
    ln -sv "$prefix""$i" frames/$f.$ext
    f=$(($f+1))
done
