#!/bin/bash

if [ "$#" -gt 1 ]; then
    crf="$2"
else
    crf=20
fi

outputname="${1%.*}.ffmpeg.mp4"

ffmpeg -i "$1" \
       -c:v libx265 \
       -tag:v hvc1 \
       -crf "$crf" \
       -colorspace bt2020nc -color_primaries bt2020 -color_trc arib-std-b67 \
       "$outputname"
